Marked alphanumeric as deprecated
evrythng/gs1-digital-link-tools pull request #10
Opened 2020-10-12 09:45 UTC by clementh59

Set the numbers only to be the default

2020-10-19 10:13 UTC, C-D-Lewis submitted a review, later dismissed

2020-11-02 14:04 UTC, C-D-Lewis requested changes

2020-11-02 14:04 UTC, C-D-Lewis commented on src/scripts/verifier.js
> +const checkIfUriIsDeprecated = (dl) => {
Add JSDoc explaining that if an alpha mapping is present, it is considered deprecated _because_ it should be a number AI instead.

By the way, are alphanumeric aliases like `gtin` actually deprecated in the standard? Or do we just not prefer them?

2020-11-02 14:04 UTC, C-D-Lewis commented on src/scripts/verifier.js
> +            console.log(keyQualifier);
Is `console.log` required for functionality?

2020-11-02 14:04 UTC, C-D-Lewis commented on src/scripts/verifier.js
> +        alert(`Using ${Object.keys(dl.getIdentifier())[0]} is deprecated!`);
I think throwing an error or logging in the console is more appropriate for a deprecation: `alert` blocks _all_ JS on the page, including UI responsiveness.

2020-11-02 14:04 UTC, C-D-Lewis commented on src/scripts/verifier.js
> +    Object.keys(ALPHA_MAP)
`find` / `filter` / `reduce` could probably do this in a neater fashion, but this is enough for now.

2020-11-02 14:04 UTC, C-D-Lewis commented on src/scripts/generator.js
> +  // I authorize the key qualifiers to be automatically sorted following the GRAMMAR restrictions
I don't understand this comment, can you explain/rephrase?

2020-11-02 16:55 UTC, clementh59 commented on src/data/alpha-map.json
> -  "410": "shipTo",
this file is useful only for the alert to say that you use deprecated syntax..

2020-11-03 09:45 UTC, clementh59 commented on src/scripts/verifier.js
> +const checkIfUriIsDeprecated = (dl) => {
Yes they are deprecated

2020-11-03 09:46 UTC, clementh59 commented on src/scripts/verifier.js
> +        alert(`Using ${Object.keys(dl.getIdentifier())[0]} is deprecated!`);
I'll do it in another way

2020-11-04 15:15 UTC, C-D-Lewis requested changes
One last thing...

2020-11-04 15:15 UTC, C-D-Lewis commented on src/scripts/verifier.js
> +    if (hasDeprecatedTerms) {
This can be one line:
```js
UI.divDeprecatedMessage.style.visibility = hasDeprecatedTerms ? 'visible' : 'hidden';
```

2020-11-04 15:18 UTC, C-D-Lewis approved these changes
Good work!

2020-11-04 15:21 UTC, merged